const fs = require('fs')
const path = require('path')
const { spawn } = require('child_process')
const nativeTests = new Set(['browserVisual.test.js', 'customModsSmoke.test.js', 'googleAuth.test.js'])
const files = fs.readdirSync(__dirname)
  .filter(name => name.endsWith('.test.js') && !nativeTests.has(name))
  .sort().map(name => path.join(__dirname, name))
const child = spawn(process.execPath, ['--test'].concat(files), { stdio: 'inherit' })
child.on('error', error => { console.error(error); process.exitCode = 1 })
child.on('exit', code => { process.exitCode = code == null ? 1 : code })
